export interface ProductDetailSpec {
  label: string;
  value: string;
}

export interface ProductItem {
  id: string;
  name: string;
  modelCode: string;
  categoryId: string;
  categoryName: string;
  description: string;
  image: string;
  priceEstimate?: string;
  badge?: string;
  keySpecs: string[];
  detailedSpecs: ProductDetailSpec[];
  features: string[];
  applications: string[];
  inStock: boolean;
  warranty: string;
}

export interface ProductCategoryOption {
  id: string;
  name: string;
  description: string;
}

export const PRODUCT_CATEGORIES: ProductCategoryOption[] = [
  { id: "all", name: "All Products", description: "Complete Felicity Solar & Energy Equipment Catalog" },
  { id: "solar-panels", name: "Solar Panels", description: "Monocrystalline & Bifacial Photovoltaic Modules" },
  { id: "batteries", name: "Batteries", description: "LiFePO4 Lithium Energy Storage & Wall-Mounted Powerwalls" },
  { id: "inverters", name: "Hybrid Inverters", description: "Pure Sine Wave Hybrid Solar Inverters & Charge Control Units" },
  { id: "street-lights", name: "Street Lights", description: "All-in-One & Split-Type Commercial Solar LED Lighting" },
  { id: "charge-controllers", name: "Charge Controllers", description: "High-Efficiency MPPT Solar Charge Regulators" },
  { id: "flood-lights", name: "Flood & Projector Lights", description: "Heavy-Duty IP67 Outdoor Floodlights & Portable Lamps" },
];

export const PRODUCTS_DATA: ProductItem[] = [
  // Solar Panels
  {
    id: "felicity-mono-175w",
    name: "Felicity M-175W MONO Solar Panel",
    modelCode: "FL-SP-175W-M",
    categoryId: "solar-panels",
    categoryName: "Solar Panels",
    description: "The Felicity M-175W Monocrystalline Solar Panel delivers exceptional conversion efficiency in a compact, durable footprint. Engineered with advanced low-light cell technology, it provides dependable power generation for residential roofs, streetlights, RVs, and backup power systems.",
    image: "/assets/products/solar-panels.png",
    badge: "Compact Efficiency",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["175W Rated Power", "Monocrystalline Cells", "High Low-Light Yield", "IP67 Waterproof"],
    detailedSpecs: [
      { label: "Peak Power (Pmax)", value: "175W" },
      { label: "Cell Type", value: "Monocrystalline Silicon" },
      { label: "Module Efficiency", value: "21.2%" },
      { label: "Open Circuit Voltage (Voc)", value: "22.4V" },
      { label: "Short Circuit Current (Isc)", value: "9.85A" },
      { label: "Maximum Power Voltage (Vmp)", value: "18.6V" },
      { label: "Maximum Power Current (Imp)", value: "9.41A" },
      { label: "Junction Box Rating", value: "IP67 Rated" },
      { label: "Dimensions", value: "1480 x 670 x 30 mm" },
      { label: "Weight", value: "11.2 kg" },
    ],
    features: [
      "High cell efficiency with quality silicon materials for long-term output stability",
      "Rigorous quality control meeting highest international standard ISO9001",
      "High transmittance low iron tempered glass with enhanced stiffness and impact resistance",
      "Advanced encapsulation material with multilayer sheet lamination for superior protection",
    ],
    applications: [
      "Residential rooftop solar arrays",
      "Off-grid DC lighting systems & kiosks",
      "Solar street light installations",
      "Telecommunication & remote monitoring stations",
    ],
    inStock: true,
    warranty: "25-Year Linear Power Output Warranty",
  },
  {
    id: "felicity-mono-450w",
    name: "Felicity M-450W MONO Panel",
    modelCode: "FL-SP-450W-HC",
    categoryId: "solar-panels",
    categoryName: "Solar Panels",
    description: "High-capacity 450W monocrystalline solar module crafted with half-cut cell technology to minimize internal electrical resistance, reduce shade losses, and maximize daily power yield for home energy storage and commercial building projects.",
    image: "/assets/products/solar-panels.png",
    badge: "Best Seller",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["450W Output Power", "Half-Cut Cell Tech", "Anti-PID Protection", "25-Yr Performance Warranty"],
    detailedSpecs: [
      { label: "Peak Power (Pmax)", value: "450W" },
      { label: "Cell Configuration", value: "144 Half-Cut Monocrystalline Cells" },
      { label: "Module Efficiency", value: "20.9%" },
      { label: "Open Circuit Voltage (Voc)", value: "49.5V" },
      { label: "Short Circuit Current (Isc)", value: "11.58A" },
      { label: "Max System Voltage", value: "1500V DC" },
      { label: "Front Glass", value: "3.2mm Anti-Reflective Tempered Glass" },
      { label: "Frame", value: "Anodized Aluminum Alloy" },
      { label: "Dimensions", value: "2094 x 1038 x 35 mm" },
      { label: "Weight", value: "23.5 kg" },
    ],
    features: [
      "Half-cell technology reduces shade impact and operating temperature",
      "Excellent PID (Potential Induced Degradation) resistance certified",
      "Heavy load endurance: 2400 Pa wind load and 5400 Pa snow load",
      "Multi-busbar technology for better light absorption and current collection",
    ],
    applications: [
      "Commercial & Industrial Solar Power Plants",
      "Residential Hybrid Solar & Battery Systems",
      "Agricultural Solar Water Pumping Systems",
    ],
    inStock: true,
    warranty: "25-Year Performance Warranty (12-Year Material)",
  },
  {
    id: "felicity-mono-550w",
    name: "Felicity M-550W High-Efficiency MONO Panel",
    modelCode: "FL-SP-550W-BF",
    categoryId: "solar-panels",
    categoryName: "Solar Panels",
    description: "Ultra-high output 550W solar module optimized for large-scale commercial solar installations and heavy industrial microgrids. Engineered for maximum wattage output per square meter with superior high-temperature performance coefficient.",
    image: "/assets/products/solar-panels.png",
    badge: "Industrial Grade",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["550W Peak Rating", "Bifacial Energy Gain", "Heavy-Duty Frame", "Extreme Temp Tolerance"],
    detailedSpecs: [
      { label: "Peak Power (Pmax)", value: "550W" },
      { label: "Cell Technology", value: "N-Type TOPCon Monocrystalline" },
      { label: "Module Efficiency", value: "21.5%" },
      { label: "Open Circuit Voltage (Voc)", value: "50.1V" },
      { label: "Short Circuit Current (Isc)", value: "14.02A" },
      { label: "Bifaciality", value: "70% ± 5%" },
      { label: "Max System Voltage", value: "1500V DC" },
      { label: "Dimensions", value: "2278 x 1134 x 35 mm" },
      { label: "Weight", value: "28.0 kg" },
    ],
    features: [
      "TOPCon technology delivers higher efficiency and lower temperature degradation",
      "Bifacial design captures rear-side light gain up to 25% extra energy",
      "Optimized for high-temperature equatorial climates with lower power degradation rate",
    ],
    applications: [
      "Utility-scale Solar Farms",
      "Factory & Warehouse Rooftops",
      "Heavy Industrial Power Systems",
    ],
    inStock: true,
    warranty: "30-Year Bifacial Linear Power Warranty",
  },

  // Batteries
  {
    id: "felicity-lifepo4-12v-200ah",
    name: "Felicity 12.8V 200Ah Lithium LiFePO4 Battery",
    modelCode: "FL-BAT-12.8V-200AH",
    categoryId: "batteries",
    categoryName: "Batteries",
    description: "High-performance 12.8V 200Ah LiFePO4 battery pack providing deep discharge capability, 6000+ lifecycle durability, and an integrated intelligent Battery Management System (BMS) for dependable home energy storage and off-grid power.",
    image: "/assets/products/batteries.png",
    badge: "Popular Storage",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["2.56kWh Usable Capacity", "LiFePO4 Chemistry", "6000+ Cycle Life", "Built-in Smart BMS"],
    detailedSpecs: [
      { label: "Nominal Voltage", value: "12.8V" },
      { label: "Nominal Capacity", value: "200Ah" },
      { label: "Energy Capacity", value: "2560Wh (2.56kWh)" },
      { label: "Chemistry", value: "Lithium Iron Phosphate (LiFePO4)" },
      { label: "Cycle Life", value: "> 6000 cycles @ 80% DOD" },
      { label: "Max Charge Voltage", value: "14.6V" },
      { label: "Max Continuous Current", value: "100A" },
      { label: "Operating Temperature", value: "-20°C to 65°C" },
      { label: "Dimensions", value: "522 x 240 x 218 mm" },
      { label: "Weight", value: "22.5 kg" },
    ],
    features: [
      "Built-in Smart BMS with over-charge, over-discharge, over-current and thermal protection",
      "Drop-in lead-acid replacement with 3x longer lifespan and 50% lighter weight",
      "Zero maintenance required throughout operational service life",
      "Parallel expansion capability for higher capacity requirements",
    ],
    applications: [
      "Home Energy Storage Systems",
      "Inverter Backup Power Banks",
      "Marine & RV Mobile Power",
      "Solar Streetlight Energy Storage",
    ],
    inStock: true,
    warranty: "5-Year Manufacturer Warranty",
  },
  {
    id: "felicity-powerwall-48v-100ah",
    name: "Felicity 48V 100Ah Wall-Mounted Powerwall",
    modelCode: "FL-LPBF48100-M",
    categoryId: "batteries",
    categoryName: "Batteries",
    description: "Sleek wall-mounted 5.12kWh lithium battery storage system with active cell balancing, RS485/CAN communication protocol, and seamless plug-and-play integration with hybrid solar inverters.",
    image: "/assets/products/batteries.png",
    badge: "Flagship Powerwall",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["5.12kWh Storage", "Wall-Mount Compact Design", "Parallel Expansion Capable", "LCD Status Screen"],
    detailedSpecs: [
      { label: "Nominal Voltage", value: "51.2V" },
      { label: "Nominal Capacity", value: "100Ah" },
      { label: "Total Energy", value: "5120Wh (5.12kWh)" },
      { label: "Recommend DOD", value: "95%" },
      { label: "Communication Ports", value: "CAN2.0, RS485" },
      { label: "Max Discharge Current", value: "120A" },
      { label: "Parallel Modules", value: "Up to 12 units in parallel" },
      { label: "IP Protection Rating", value: "IP21 Indoor Wall-Mount" },
      { label: "Dimensions", value: "680 x 485 x 200 mm" },
      { label: "Weight", value: "46.0 kg" },
    ],
    features: [
      "High security grade A LiFePO4 cells with thermal runaway prevention",
      "Intelligent LCD touchscreen showing state-of-charge, voltage, and cell diagnostics",
      "Compatible with Felicity, Growatt, Deye, Victron, and major hybrid inverter brands",
      "Compact wall-mount form factor saves floor space in residential installations",
    ],
    applications: [
      "Residential Whole-Home Backup",
      "Commercial Office Power Reliability",
      "Critical Telecom Infrastructure",
    ],
    inStock: true,
    warranty: "5-Year Full Warranty (10-Year Expected Service Life)",
  },
  {
    id: "felicity-stackable-48v-200ah",
    name: "Felicity 48V 200Ah Stackable Lithium Battery (10kWh)",
    modelCode: "FL-LPBF48200-S",
    categoryId: "batteries",
    categoryName: "Batteries",
    description: "Modular high-capacity 10kWh stackable lithium storage tower engineered for commercial energy storage, luxury residences, and heavy power applications needing scalable reserve capacity.",
    image: "/assets/products/batteries.png",
    badge: "High Capacity",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["10.24kWh Capacity", "Stackable Modular Design", "Heavy-Duty 150A BMS", "Smart CAN/RS485 Bus"],
    detailedSpecs: [
      { label: "Nominal Voltage", value: "51.2V" },
      { label: "Nominal Capacity", value: "200Ah" },
      { label: "Total Usable Energy", value: "10.24kWh" },
      { label: "Chemistry", value: "Grade-A LiFePO4" },
      { label: "Max Continuous Current", value: "150A" },
      { label: "Peak Surge Current", value: "200A (3 sec)" },
      { label: "Expandability", value: "Stackable up to 60kWh total" },
      { label: "Dimensions", value: "650 x 440 x 360 mm" },
      { label: "Weight", value: "88.0 kg" },
    ],
    features: [
      "Modular stackable design requires no messy external cabling between modules",
      "High power output capability handles heavy inductive loads like air conditioners and pumps",
      "Advanced multi-tier BMS with auto-balancing and cloud monitoring ready",
    ],
    applications: [
      "Large Residential Mansions",
      "Hospitals & Medical Clinics",
      "Supermarkets & Commercial Plazas",
    ],
    inStock: true,
    warranty: "5-Year Warranty",
  },

  // Inverters
  {
    id: "felicity-ivem-5kw",
    name: "Felicity IVEM 5KW Hybrid Solar Inverter",
    modelCode: "FL-IVEM-5048",
    categoryId: "inverters",
    categoryName: "Hybrid Inverters",
    description: "Advanced pure sine wave hybrid inverter with built-in 80A MPPT charge controller, flexible grid/generator dual inputs, and instant automatic transfer switchover (<10ms) for zero power disruption.",
    image: "/assets/products/inverters.png",
    badge: "Top Choice",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["5000W Pure Sine Wave", "80A MPPT Controller", "Grid & Generator Dual Input", "WiFi Remote Control"],
    detailedSpecs: [
      { label: "Rated Output Power", value: "5000W / 5000VA" },
      { label: "DC Input Voltage", value: "48V DC" },
      { label: "Output Waveform", value: "Pure Sine Wave" },
      { label: "MPPT Tracker", value: "Single MPPT (80A)" },
      { label: "Max PV Input Power", value: "5000W" },
      { label: "Max PV Open Circuit", value: "500V DC" },
      { label: "MPPT Operating Voltage", value: "120V ~ 450V DC" },
      { label: "Transfer Time", value: "10ms (Personal Computers), 20ms (Home Appliances)" },
      { label: "Efficiency", value: "93% Peak" },
      { label: "Dimensions", value: "468 x 330 x 120 mm" },
      { label: "Weight", value: "11.0 kg" },
    ],
    features: [
      "Configurable AC/Solar input priority via user-friendly LCD setting interface",
      "Compatible to main voltage or generator power with auto generator dry contact start signal",
      "Overload, over-temperature, and short-circuit electronic protection",
      "Smart battery charger design for optimized battery lifecycle performance",
    ],
    applications: [
      "Home Solar Systems",
      "Small Businesses & Eateries",
      "School & Laboratory Backup Systems",
    ],
    inStock: true,
    warranty: "2-Year Manufacturer Warranty",
  },
  {
    id: "felicity-ivem-10kw-3p",
    name: "Felicity IVEM 10KW 3-Phase Solar Inverter",
    modelCode: "FL-IVEM-10048-3P",
    categoryId: "inverters",
    categoryName: "Hybrid Inverters",
    description: "Commercial-grade 10KW 3-phase hybrid solar inverter designed to power heavy inductive loads, industrial machinery, central air conditioning units, and commercial plazas directly from solar PV and battery banks.",
    image: "/assets/products/inverters.png",
    badge: "Commercial Power",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["10,000W 3-Phase Output", "Dual MPPT Channels", "Touchscreen Color Interface", "Built-in Surge Protection"],
    detailedSpecs: [
      { label: "Rated Output Power", value: "10,000W (10kW)" },
      { label: "Output Phase", value: "3-Phase / 400V AC" },
      { label: "Battery Voltage", value: "48V DC" },
      { label: "Max PV Array Power", value: "15,000W" },
      { label: "MPPT Channels", value: "2 Independent Trackers" },
      { label: "Max Charge Current", value: "200A Combined" },
      { label: "Parallel Capability", value: "Up to 6 units (60kW total)" },
      { label: "Communication", value: "RS485, CAN, Wi-Fi, GPRS" },
      { label: "Dimensions", value: "620 x 440 x 220 mm" },
      { label: "Weight", value: "32.0 kg" },
    ],
    features: [
      "Dual MPPT controllers allow dual roof orientation arrays for maximum daily solar harvest",
      "Zero export grid feedback setting for areas with grid feeding regulations",
      "Comprehensive color touchscreen dashboard with historical power logging",
    ],
    applications: [
      "Cold Storage Facilities",
      "Manufacturing Factories & Mills",
      "Commercial Shopping Malls & Hotels",
    ],
    inStock: true,
    warranty: "2-Year Factory Warranty",
  },

  // Street Lights
  {
    id: "felicity-street-light-100w",
    name: "Felicity All-in-One Solar Street Light 100W",
    modelCode: "FL-SL-100W-AIO",
    categoryId: "street-lights",
    categoryName: "Street Lights",
    description: "Integrated outdoor solar streetlight combining high-efficiency monocrystalline solar panel, MPPT charge controller, intelligent microwave radar motion sensor, and ultra-bright Bridgelux LED array into a seamless rustproof casing.",
    image: "/assets/products/street-lights.png",
    badge: "All-In-One",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["100W Ultra LED Output", "Microwave Motion Sensor", "Auto Dusk-to-Dawn Control", "Rustproof Aluminum Alloy"],
    detailedSpecs: [
      { label: "LED Power Rating", value: "100W Super Bright LED" },
      { label: "Luminous Flux", value: "13,000 Lumens" },
      { label: "Solar Panel", value: "18V 60W High-Efficiency Mono" },
      { label: "Battery", value: "12.8V 30Ah LiFePO4" },
      { label: "Sensor Mode", value: "Radar Sensor / Time Control / Dimming" },
      { label: "Charging Time", value: "6 to 8 hours direct sun" },
      { label: "Lighting Time", value: "3 to 5 rainy/cloudy days reserve" },
      { label: "Ingress Protection", value: "IP65 Weatherproof" },
      { label: "Installation Height", value: "6 to 8 meters" },
    ],
    features: [
      "Automatic energy saving mode dims to 30% brightness when no motion detected",
      "Corrosion-resistant aluminum alloy housing withstands coastal saline humidity",
      "Tool-free easy pole mounting system",
    ],
    applications: [
      "Estate Streets & Residential Avenues",
      "University Campuses & Parks",
      "Factory Perimeter Security Lighting",
    ],
    inStock: true,
    warranty: "3-Year Warranty",
  },
  {
    id: "felicity-street-light-200w-split",
    name: "Felicity Split-Type Solar Street Lamp 200W",
    modelCode: "FL-SL-200W-SPLIT",
    categoryId: "street-lights",
    categoryName: "Street Lights",
    description: "Heavy-duty split solar streetlight with external high-wattage monocrystalline solar panel, enabling independent tilt orientation for optimal sun alignment and maximum commercial highway lumen coverage.",
    image: "/assets/products/street-lights.png",
    badge: "Highway Grade",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["200W High Lumen LED", "Adjustable Solar Mount", "Multi-Night Power Reserve", "IP65 Outdoor Rated"],
    detailedSpecs: [
      { label: "LED Power Output", value: "200W High-Lumen Array" },
      { label: "Luminous Efficacy", value: "160 lm/W" },
      { label: "Solar Panel", value: "18V 120W External Mono" },
      { label: "Battery Capacity", value: "12.8V 60Ah LiFePO4" },
      { label: "Color Temperature", value: "6000K Daylight White" },
      { label: "Mounting Arm Diameter", value: "60mm Standard Pole" },
      { label: "Operating Temp", value: "-20°C ~ +60°C" },
    ],
    features: [
      "Separated solar panel can be oriented precisely south regardless of road direction",
      "High power LiFePO4 battery pack mounted inside heavy-duty die-cast lamp housing",
      "Programmable multi-stage timer profile with intelligent battery saving algorithm",
    ],
    applications: [
      "Municipal Highways & Expressways",
      "Airport & Logistics Terminals",
      "Commercial Parking Lots",
    ],
    inStock: true,
    warranty: "3-Year Warranty",
  },

  // Charge Controllers
  {
    id: "felicity-mppt-60a",
    name: "Felicity MPPT 60A Solar Charge Controller",
    modelCode: "FL-MPPT-60A",
    categoryId: "charge-controllers",
    categoryName: "Charge Controllers",
    description: "Maximum Power Point Tracking (MPPT) solar charge controller delivering over 98.5% tracking conversion efficiency, multi-stage battery charging, and full digital telemetry display for high-yield solar arrays.",
    image: "/assets/products/charge-controllers.png",
    badge: "High Efficiency",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["60A Continuous Current", "98.5% MPPT Efficiency", "Auto 12V/24V/48V Detection", "Overcharge & Short Safeguard"],
    detailedSpecs: [
      { label: "Max Charge Current", value: "60A" },
      { label: "System Voltage", value: "12V / 24V / 36V / 48V Auto Select" },
      { label: "Max PV Input Voltage", value: "150V DC" },
      { label: "Max PV Input Power", value: "2880W (at 48V battery system)" },
      { label: "MPPT Efficiency", value: "≥ 98.5%" },
      { label: "Battery Type presets", value: "Sealed, Gel, Flooded, LiFePO4, User Custom" },
      { label: "Cooling Method", value: "Heavy Aluminum Heat Sink + Fan" },
      { label: "Dimensions", value: "280 x 190 x 85 mm" },
    ],
    features: [
      "Ultra-fast tracking speed with peak detection accuracy",
      "Multi-stage charging algorithm extends battery bank operational lifespan",
      "Comprehensive electronic protection against reverse polarity, over-voltage, and overheating",
    ],
    applications: [
      "Off-Grid Cabin & Cottage Systems",
      "Custom Solar Array Upgrade",
      "Telecom Telemetry Power",
    ],
    inStock: true,
    warranty: "2-Year Warranty",
  },
  {
    id: "felicity-mppt-80a",
    name: "Felicity MPPT 80A Heavy-Duty Controller",
    modelCode: "FL-MPPT-80A-HD",
    categoryId: "charge-controllers",
    categoryName: "Charge Controllers",
    description: "High-capacity 80A MPPT controller supporting wide PV input voltage up to 150V DC, heavy-duty aluminum heat sink cooling, and precision external battery temperature compensation sensor.",
    image: "/assets/products/charge-controllers.png",
    badge: "Heavy-Duty",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["80A Maximum Charge", "Up to 150V PV Input", "Aluminum Heat Sink Chassis", "Programmable Presets"],
    detailedSpecs: [
      { label: "Max Charge Current", value: "80A" },
      { label: "Nominal System Voltage", value: "12V / 24V / 48V Auto Recognition" },
      { label: "Max PV Array Input", value: "3840W (at 48V battery system)" },
      { label: "Conversion Efficiency", value: "99.0% Peak" },
      { label: "Self Loss Power", value: "≤ 2W" },
      { label: "Display Interface", value: "Backlit Multi-Function LCD" },
    ],
    features: [
      "Wide MPPT operating voltage window allows longer PV string connections",
      "Supports parallel operation of multiple charge controllers for massive solar arrays",
      "RS485 communication port for remote monitoring software integration",
    ],
    applications: [
      "Large Off-Grid Power Installations",
      "Commercial Battery Charging Hubs",
    ],
    inStock: true,
    warranty: "2-Year Warranty",
  },

  // Flood & Projector Lights
  {
    id: "felicity-flood-light-200w",
    name: "Felicity Heavy-Duty Solar Flood Light 200W",
    modelCode: "FL-FL-200W-IP67",
    categoryId: "flood-lights",
    categoryName: "Flood & Projector Lights",
    description: "IP67 fully waterproof outdoor solar flood light with rugged die-cast aluminum casing, high-lumen optical lenses, wireless IR remote control, and dedicated high-output solar charging panel.",
    image: "/assets/products/floor-light.png",
    badge: "IP67 Outdoor",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["200W High Output Flood", "IP67 Fully Waterproof", "Wireless IR Remote Control", "Reinforced Glass"],
    detailedSpecs: [
      { label: "LED Power Output", value: "200W High Output Matrix" },
      { label: "Beam Angle", value: "120° Wide Coverage" },
      { label: "Solar Panel", value: "6V 35W High Efficiency Polycrystalline" },
      { label: "Battery", value: "3.2V 30Ah LiFePO4" },
      { label: "Lighting Area", value: "Up to 250 m²" },
      { label: "Control Mode", value: "Light Sensor + Remote Control Timer" },
      { label: "Cable Length", value: "5 Meters Waterproof Cable" },
    ],
    features: [
      "High impact tempered glass cover resistant to extreme heat and storm impact",
      "Adjustable mounting bracket for wall, pole, or ground flood illumination",
      "Included wireless remote control with 3h, 5h, 8h auto-off timer options",
    ],
    applications: [
      "Building Facades & Billboards",
      "Residential Compound & Security Yard",
      "Construction Sites & Farms",
    ],
    inStock: true,
    warranty: "2-Year Warranty",
  },
  {
    id: "felicity-projector-lamp-150w",
    name: "Felicity Portable Solar Projector Lamp 150W",
    modelCode: "FL-PL-150W-PORT",
    categoryId: "flood-lights",
    categoryName: "Flood & Projector Lights",
    description: "Versatile portable solar projector lamp equipped with foldable kickstand, emergency power bank USB output for mobile device charging, and adjustable 3-stage color temperature for jobsites, camping, and outdoor events.",
    image: "/assets/products/floor-light.png",
    badge: "Multi-Functional",
    priceEstimate: "Contact for Wholesale / Retail Quote",
    keySpecs: ["150W Portable Flood", "Built-in USB Powerbank", "3 Color Temp Modes", "5-Year Battery Lifespan"],
    detailedSpecs: [
      { label: "Power Rating", value: "150W Compact Flood" },
      { label: "USB Output", value: "5V / 2A Fast Charge Port" },
      { label: "Light Modes", value: "Cool White / Warm White / SOS Emergency Strobe" },
      { label: "Battery Capacity", value: "3.2V 15Ah LiFePO4" },
      { label: "Run Time", value: "8 to 14 Hours depending on mode" },
      { label: "Chassis", value: "Impact-Resistant ABS + Rubber Armor" },
    ],
    features: [
      "360-degree rotating kickstand and strong magnetic back mount",
      "Emergency SOS red & blue strobe light setting for roadside breakdowns",
      "Dual charging input: Solar panel charging or USB-C fast AC charging",
    ],
    applications: [
      "Outdoor Night Operations & Mechanics",
      "Camping & Event Lighting",
      "Emergency Home Backup Light & Phone Charger",
    ],
    inStock: true,
    warranty: "2-Year Warranty",
  },
];
